### ISSUE TITLE
Dogfood

### ISSUE THREAD

**Issue by patelnav** [bilby91/ganban#5]
You know what would be great to track Ganban progress, issues and tasks, and make sure upgrades are done right? A hosted ganban!

I see you guys have an AppEngine project called "ganban-1130" already. I've created another one called "gan-ban" (little AppEngine ID naming trick 😉). 

I've added you guys on there, so as we're adding features and doing upgrades, we can make sure everything works well. Check it out: http://gan-ban.appspot.com

**Comment by bilby91** [comment]
@patelnav Can you verify new features are good ? 

Also, we can add a demo link in the README!

**Comment by bilby91** [comment]
@patelnav Also, I added you as a collaborator, you have MERGE permissions now :)
